//
//  ProgressBarDraw.swift
//  AudioHackers
//
//  Created by RichRuais on 6/4/17.
//  Copyright (c) 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    public class func drawProgrssBar(frame frame: CGRect = CGRect(x: 1, y: -1, width: 300, height: 16), progress: CGFloat = 210) {
        //// Color Declarations
        let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let color2 = UIColor(red: 0.415, green: 0.451, blue: 0.887, alpha: 1.000)

        //// Progrss Border Drawing
        let progrssBorderPath = UIBezierPath(roundedRect: CGRect(x: frame.minX, y: frame.minY, width: floor((frame.width) * 0.99500) + 0.5, height: 14), cornerRadius: 7)
        color.setFill()
        progrssBorderPath.fill()
        color.setStroke()
        progrssBorderPath.lineWidth = 4
        progrssBorderPath.stroke()


        //// Progress Active Drawing
        let progressActivePath = UIBezierPath(roundedRect: CGRect(x: 1, y: 1, width: progress, height: 14), cornerRadius: 7)
        color2.setFill()
        progressActivePath.fill()
    }

}
